main: de.kumpelblase2.dragonslair.DragonsLairMain
author: kumpelblase2
version: 2.3.3
name: Dragons Lair
depend: [RemoteEntities]
softdepend: [Citizens, Vault]
commands:
    dragonslair:
        description: All commands of Dragons Lair
        aliases: [dl]

permissions:
    dragonslair.config:
        description: Gives the ability to use the configuration
        default: op